{{- if .Values.piHoleHostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: pihole
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.piHoleHostname }}
    http:
      paths:
      - backend:
          service:
            name: pihole-svc
            port:
              number: 580
        path: /
        pathType: Prefix
{{- end }}
