apiVersion: v1
kind: Service
metadata:
  name: pihole-svc
  namespace: pihole
spec:
  externalTrafficPolicy: Local # Required to keep original client ip in pihole logs
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dhcp
    port: 67
    protocol: UDP
    targetPort: 67
  - name: http
    port: 580
    protocol: TCP
    targetPort: 80
  # - name: https
  #   port: 5443
  #   protocol: TCP
  #   targetPort: 443
  type: LoadBalancer
